"""Картинки для карточек заданий: предметы 16 × 16 в стиле двора.

Записываются исходниками src/yard/item_*.txt в формате art/pixel.
Запуск: python tools/make_items.py, затем python tools/build.py.
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "yard")

# Каждый предмет — 16 строк по 16 символов палитры; «.» — прозрачно.
ITEMS = {
    "item_water": ("миска воды", [
        "................",
        "................",
        "................",
        "................",
        "................",
        "......u..u......",
        ".......u........",
        "..KKKKKKKKKKKK..",
        "..KaauuuuuuaaK..",
        "..KuuuuuuuuuuK..",
        "...KmmmmmmmmK...",
        "...KmmmmmmmmK...",
        "....KmmmmmmK....",
        ".....KKKKKK.....",
        "................",
        "................",
    ]),
    "item_stickers": ("наклейки", [
        "................",
        "................",
        "..KKKKKKKKKK....",
        "..KccccccccK....",
        "..KcPPcccYcK....",
        "..KcPPccYYYKKK..",
        "..KccccccYcK.K..",
        "..KcccuucccKcK..",
        "..KccuuuuccKcK..",
        "..KcccuucccKcK..",
        "..KccccccccKcK..",
        "..KKKKKKKKKKcK..",
        "....KccccccccK..",
        "....KKKKKKKKKK..",
        "................",
        "................",
    ]),
    "item_candy": ("конфета", [
        "................",
        "................",
        "................",
        "................",
        "................",
        ".KK..........KK.",
        ".KRK..KKKK..KRK.",
        ".KRRKKRnRRKKRRK.",
        ".KRRKRnRRRRKRRK.",
        ".KRK.KRRRrK.KRK.",
        ".KK...KKKK...KK.",
        "................",
        "................",
        "................",
        "................",
        "................",
    ]),
    "item_candies": ("гора конфет", [
        "................",
        "................",
        "......KKKK......",
        ".....KRnRRK.....",
        "....KKRRrKK.....",
        "...KYYK..KPPK...",
        "..KYyYYKKPnPPK..",
        "..KYYYOKKPPPpK..",
        "...KKKKuuKKKK...",
        "..KRRKuauuKRRK..",
        ".KRnRKuuuuKRnRK.",
        ".KRRrKKKKKKRRrK.",
        ".KKKKYYYOKKKKKK.",
        "....KYyYYOK.....",
        ".....KKKKK......",
        "................",
    ]),
    "item_notebook": ("тетрадка", [
        "................",
        "................",
        "...KKKKKKKKK....",
        "...KuKcccccKK...",
        "...KuKcccccKcK..",
        "...KuKcmmmccKK..",
        "...KuKcccccccK..",
        "...KuKcmmmmmcK..",
        "...KuKcccccccK..",
        "...KuKcmmmmmcK..",
        "...KuKcccccccK..",
        "...KuKcmmmmmcK..",
        "...KuKcccccccK..",
        "...KKKKKKKKKKK..",
        "................",
        "................",
    ]),
    "item_coat": ("шуба", [
        "................",
        ".....KK..KK.....",
        "....KccKKccK....",
        "...KTTcccTTTK...",
        "..KTTTKccKTTTK..",
        ".KTTTTKTTKTTTTK.",
        ".KTTtKTTTTKtTTK.",
        ".KTTtKTTYTKtTTK.",
        ".KccKKTTTTKKccK.",
        "..KK.KTTYTK.KK..",
        ".....KTTTTK.....",
        ".....KTTTTK.....",
        ".....KccccK.....",
        ".....KKKKKK.....",
        "................",
        "................",
    ]),
    "item_house": ("дом", [
        "................",
        ".......KK.......",
        "......KRRK..KK..",
        ".....KRRRRK.KK..",
        "....KRRRRRRKKK..",
        "...KRRRRRRRRK...",
        "..KrrrrrrrrrrK..",
        "...KyyyyyyyyK...",
        "...KyKKyyKKyK...",
        "...KyKuyyKuyK...",
        "...KyKKyyKKyK...",
        "...KyyyKKyyyK...",
        "...KyyyKTKyyK...",
        "...KyyyKTKyyK...",
        "...KKKKKKKKKK...",
        "................",
    ]),
    "item_bike": ("велосипед", [
        "................",
        "................",
        "................",
        "..........KK....",
        "...KK.....KR....",
        "....KR...KR.....",
        ".....KRRRRK.....",
        "..KKKKRKKRKKK...",
        ".KmK.KRK.KmmK...",
        "KmcmKKRKKmKcmK..",
        "KmcmK.KRKmKcmK..",
        "KmmmK..KKmmmmK..",
        ".KKK......KKK...",
        "................",
        "................",
        "................",
    ]),
    "item_ticket": ("билет в кино", [
        "................",
        "................",
        "................",
        "................",
        ".KKKKKKKKKKKKKK.",
        ".KYYYYYKYYYYYYK.",
        "KYYRRYYKYYKKYYYK",
        ".KYRRYYKYYKKYYK.",
        ".KYYYYYKYYYYYYK.",
        "KYYyyYYKYKKKKYYK",
        ".KYYYYYKYYYYYYK.",
        ".KKKKKKKKKKKKKK.",
        "................",
        "................",
        "................",
        "................",
    ]),
    "item_toycar": ("игрушечная машинка", [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "......KKKK......",
        ".....KaaaRK.....",
        "...KKRRRRRRKK...",
        "...KRRRRRRRRK...",
        "...KKmKKKKmKK...",
        "....KKK..KKK....",
        "................",
        "................",
        "................",
    ]),
    "item_car": ("настоящая машина", [
        "................",
        "................",
        "................",
        ".....KKKKKK.....",
        "....KaaKaaaK....",
        "...KaaaKaaaaK...",
        ".KKuuuuuuuuuKKK.",
        "KuuuuuuuuuuuuuuK",
        "KuYuuuuuuuuuuYuK",
        "KuuuuuuuuuuuuuuK",
        "KKKmmKKKKKKmmKKK",
        "..KmcmK..KmcmK..",
        "..KmmmK..KmmmK..",
        "...KKK....KKK...",
        "................",
        "................",
    ]),
    "item_clock": ("часы", [
        "................",
        ".....KKKKKK.....",
        "...KKccccccKK...",
        "..KcccccKccccK..",
        "..KcccccKccccK..",
        ".KcccccKKcccccK.",
        ".KcccccKKccccRK.",
        ".KcccccKKKKKKcK.",
        ".KccccccccccccK.",
        ".KccccccccccccK.",
        "..KccccccccccK..",
        "..KccccccccccK..",
        "...KKccccccKK...",
        ".....KKKKKK.....",
        "................",
        "................",
    ]),
    "item_hourglass": ("песочные часы — подождать", [
        "................",
        "...KKKKKKKKKK...",
        "...KTTTTTTTTK...",
        "....KaaaaaaK....",
        "....KaYYYYaK....",
        ".....KaYYaK.....",
        "......KaYK......",
        "......KYaK......",
        ".....KaaYaK.....",
        "....KaaYYaaK....",
        "....KaYYYYaK....",
        "....KYYYYYYK....",
        "...KTTTTTTTTK...",
        "...KKKKKKKKKK...",
        "................",
        "................",
    ]),
    "item_yes": ("хватит", [
        "................",
        "................",
        "................",
        "............KK..",
        "...........KEEK.",
        "..........KEEK..",
        ".KK......KEEK...",
        "KEEK....KEEK....",
        ".KEEK..KEEK.....",
        "..KEEKKEEK......",
        "...KEEEEK.......",
        "....KEEK........",
        ".....KK.........",
        "................",
        "................",
        "................",
    ]),
    "item_no": ("не хватит", [
        "................",
        "................",
        "................",
        "..KK........KK..",
        ".KRRK......KRRK.",
        "..KRRK....KRRK..",
        "...KRRK..KRRK...",
        "....KRRKKRRK....",
        ".....KRRRRK.....",
        "....KRRKKRRK....",
        "...KRRK..KRRK...",
        "..KRRK....KRRK..",
        ".KRRK......KRRK.",
        "..KK........KK..",
        "................",
        "................",
    ]),
    "item_empty_bowl": ("пустая миска — голодный", [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "..KKKKKKKKKKKK..",
        "..KzzzzzzzzzzK..",
        "..KzzzzzzzzzzK..",
        "...KmmmmmmmmK...",
        "...KmmmmmmmmK...",
        "....KmmmmmmK....",
        ".....KKKKKK.....",
        "................",
        "................",
    ]),
    "item_cake": ("торт со свечами — экран подарка", [
        "................",
        "...Y....Y....Y..",
        "..YOY..YOY..YOY.",
        "...K....K....K..",
        "...P....u....P..",
        "...P....u....P..",
        ".KKKKKKKKKKKKKK.",
        ".KnnnnnnnnnnnnK.",
        ".KcPcPcPcPcPcPK.",
        ".KnnnnnnnnnnnnK.",
        ".KyyyyyyyyyyyyK.",
        ".KRRRRRRRRRRRRK.",
        ".KyyyyyyyyyyyyK.",
        "KKKKKKKKKKKKKKKK",
        "KmmmmmmmmmmmmmmK",
        ".KKKKKKKKKKKKKK.",
    ]),
    "item_shrug": ("ничего не случится?", [
        "................",
        ".....KKKKKK.....",
        "....KccccccK....",
        "...KccKKKKccK...",
        "...KcKccccKcK...",
        "...KccccccKcK...",
        "....KKccccKcK...",
        "......KcccKK....",
        "......KccK......",
        "......KccK......",
        "......KKKK......",
        "................",
        "......KKKK......",
        "......KccK......",
        "......KKKK......",
        "................",
    ]),
}

for name, (comment, rows) in ITEMS.items():
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), name
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name + ".txt"), "w", encoding="utf-8", newline="\n") as f:
        # Заголовок формата art/pixel: размер и точка привязки.
        f.write("# 16 16\n# pivot 0 0\n")
        f.write("\n".join(rows) + "\n")
print(len(ITEMS), "items")
